name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Foundry
        run: curl -L https://foundry.paradigm.xyz | bash && source /home/runner/.bashrc && foundryup

      - name: Run Forge Tests
        run: forge test -vvv
